### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by a-kong** [kashish1928/dsci-310-group-02#13]
### General
- [x] typos in `README.md` and `white_analysis.ipynb`

### Analysis: Introduction
- [x] identify and describe the dataset that was used to answer the question

### Analysis: Methods & Results
- [x] loads data from the original source on the web
- [x] performs a summary of the data set that is relevant for exploratory data analysis related to the planned classification analysis
- [x] all tables should have a table number

### Analysis: Discussion
- [x] discuss whether this is what you expected to find
- [x] discuss what impact could such findings have
- [x] discuss what future questions could this lead to

### GitHub Workflow
- [x] workflow is triggered when changes are pushed to the Dockerfile (not main)

### Reproducible Environment Using Docker
- [x] files not visible in Docker container (did not mount volumes)

### Analysis can be run reproducibly using documentation provided in the README
- [x] cannot reproduce using steps
- [x] docker compose is unnecessary and there is no docker compose file to support it 
- [x] all dependencies should be listed in `README.md`
