### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by a-kong** [kashish1928/dsci-310-group-02#22]
### Code is abstracted to functions with good function design
- [x] #27
- [x] `data_summary` function does more than 1 task
- [x] `splitdata` function has unused variables
- [x] follow [tidyverse style guide](https://style.tidyverse.org/) 

### Functions are well documented
- [x] `splitdata.R` documentation does not describe function accurately

### Helper data for tests is tractable and reproducible
- [x] helper data should have its own files

### Tests are written for each function, and work expected
- [x] incorrect file path for 2/3 tests
- [x] data loading should not be in test files

### Tests suite is of high quality
- [x] functions require more thorough testing
	- think about the possible inputs 
- [x] `data_summary` test should test for expected output

### Dependencies 
- [x] missing updated testing dependencies (`devtools`)
- [x] `tidyverse` is not installed

### Release
- [x] name it 'v2.0.0' or '2.0.0', not 'Milestone 2' to keep naming consistent

### Project file and directory structure organization
- [x] test file for `splitdata.R` named incorrectly

### GitHub Issue Milestones
- [x] missing use of milestones

### Analysis can be run reproducibly using documentation provided in the README
- [x] do not need to build Docker image (in fact, it creates an error on my end)
- [x] cannot run Docker image
- [x] Docker compose instructions is not supported
- note: you don't need to include the `docker pull` command since it will pull the image if you don't already have it when you run `docker run`

**Comment by erichy23** [comment]
Working on data_cleaning problem and making sure it meet the requirement in milestone 3 now
